//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FayeKeyILS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checkout
    {
        public long materialID { get; set; }
        public long patronLibraryID { get; set; }
        public decimal returnDate { get; set; }
        public decimal checkoutDate { get; set; }
    
        public virtual Patron Patron { get; set; }
        public virtual Material Material { get; set; }
    }
}
