//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FayeKeyILS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ILSDBEntities : DbContext
    {
        public ILSDBEntities()
            : base("name=ILSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Checkout> Checkouts { get; set; }
        public virtual DbSet<LoanLength> LoanLengths { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<Patron> Patrons { get; set; }
    }
}
