//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FayeKeyILS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.Checkouts = new HashSet<Checkout>();
        }
    
        public long Id { get; set; }
        public Nullable<long> patronLibraryID { get; set; }
        public string materialType { get; set; }
        public long materialLoanLength { get; set; }
        public string materialName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Checkout> Checkouts { get; set; }
        public virtual LoanLength LoanLength { get; set; }
        public virtual Patron Patron { get; set; }
    }
}
